Big change to starship locks, will now stay locked 10minutes after ex…
HorizonsEndMC/IonCore pull request #106
Opened 2022-04-30 22:36 UTC by SciathGH

…peration and unlocks after. No option to disable it in menu.
I cant test in my test server, so warning in advance.

2022-04-30 22:38 UTC, trainb0y1 commented
Out of curiosity what’s the reasoning behind this? Isn’t the point of ship locks to prevent ship theft while the owner is offline?

2022-04-30 22:42 UTC, SciathGH commented
No its for combat releasing, per Peters request

2022-04-30 23:58 UTC, trainb0y1 commented
Ok. Just curious lol

2022-05-01 10:21 UTC, Peter-Crawley requested changes

2022-05-01 10:21 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/PilotedStarships.kt
> -
This newline should stay.

2022-05-01 10:21 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/StarshipComputers.kt
> -
This newline should stay.

2022-05-01 10:21 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/PilotedStarships.kt
> +				player.sendFeedbackMessage(INFORMATION, "Your starship will unlock after {0}minutes", PlayerStarshipData.LOCK_TIME_MS/60000)
`{0} minutes.`

2022-05-01 10:21 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/database/schema/starships/PlayerStarshipData.kt
> +		return if (System.currentTimeMillis()-lastUsed>LOCK_TIME_MS) {
This checks if it has been more then `LOCK_TIME_MS` not less then it.

2022-05-01 10:21 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/database/schema/starships/PlayerStarshipData.kt
> +		const val LOCK_TIME_MS = 60_000 * 10
If this value is only used once then remove it and just hard code it.

2022-05-04 20:40 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/database/schema/starships/PlayerStarshipData.kt
> +		const val LOCK_TIME_MS = 60_000 * 10
Its used twice

2022-05-04 20:42 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/database/schema/starships/PlayerStarshipData.kt
> +		const val LOCK_TIME_MS = 60_000 * 10
Okay fair enough.

2022-05-15 19:17 UTC, closed without merging