Fixed allychat
HorizonsEndMC/IonCore pull request #152
Opened 2022-07-04 20:06 UTC by SciathGH

GitHub text editing is the superior IDE

2022-07-04 20:29 UTC, trainb0y1 commented
https://github.dev/ at least?
Hopefully you don’t mean like, the actual edit button

2022-07-04 20:31 UTC, trainb0y1 reviewed
Is it just me or this that “fixed(two spaces) this”

hard to tell on mobile

2022-07-04 21:31 UTC, Peter-Crawley commented
> Is it just me or this that “fixed(two spaces) this”
> 
> hard to tell on mobile

Yes

2022-07-06 22:55 UTC, Peter-Crawley requested changes

2022-07-06 22:55 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/chat/ChatChannel.kt
> +			player.sendFeedbackmessage(FeedbackType.USER_ERROR, "{0} You really hoped today would be the day we fixed  this, idiot", player.name())
```
{0}, you really hoped this would be fixed huh?
```
Would be better. Have fun changing it on your phone in France. :kekw:

2022-07-09 21:20 UTC, merged