Combat tag
HorizonsEndMC/IonCore pull request #187
Opened 2022-08-19 23:51 UTC by SciathGH

2022-08-22 17:34 UTC, Peter-Crawley requested changes
Actions check failed.

2022-08-22 17:34 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/DeactivatedPlayerStarships.kt
> +import java.util.*
No wildcard imports.

2022-08-22 17:34 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/feature/starship/DeactivatedPlayerStarships.kt
> +import java.util.*
I blame intellij

2022-08-22 20:32 UTC, Peter-Crawley requested changes

2022-08-22 20:32 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/active/ActiveStarship.kt
> +import com.sun.jna.platform.unix.X11.Atom
?????

2022-08-22 20:34 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/feature/starship/active/ActiveStarship.kt
> +import com.sun.jna.platform.unix.X11.Atom
heh?

2022-08-22 20:36 UTC, SciathGH commented
never happened

2022-08-24 16:48 UTC, Peter-Crawley commented
Janky, but i'll tollerate it for IonCore

2022-08-24 16:48 UTC, merged