Weaponset QOL, 1 to remove all weaponset targets, 1 to remove all wea…
HorizonsEndMC/IonCore pull request #192
Opened 2022-08-21 00:48 UTC by SciathGH

…ponsets containing a certain weapon.

2022-08-22 17:38 UTC, Peter-Crawley requested changes

2022-08-22 17:38 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
> +		if(weaponSet == "unsetall" && player == null){
Far too janky

2022-08-22 17:42 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
> +		if(weaponSet == "unsetall" && player == null){
how do you suggest I do it instead

2022-08-24 16:39 UTC, Peter-Crawley requested changes

2022-08-24 16:39 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/MiscStarshipCommands.kt
> +		if(weaponSet == "unsetall" && player == null){
create another command

2022-08-25 22:48 UTC, merged