Weaponsound fix  (plays at feet)
HorizonsEndMC/IonCore pull request #196
Opened 2022-08-22 17:08 UTC by SciathGH

2022-08-22 17:39 UTC, Peter-Crawley reviewed
Why?

2022-08-22 17:41 UTC, SciathGH commented
has 0 range rn

2022-08-22 17:41 UTC, SciathGH commented
Literally cannot hear it
at all

2022-08-24 16:47 UTC, Peter-Crawley requested changes

2022-08-24 16:47 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/feature/starship/subsystem/weapon/projectile/SimpleProjectile.kt
>  		loc.world.playSound(loc, soundName, SoundCategory.PLAYERS, 1.0f, pitch)
This seems like it may play the sound twice

2022-08-25 22:48 UTC, merged