Ship printing costs
HorizonsEndMC/IonCore pull request #213
Opened 2022-09-06 20:22 UTC by SciathGH

2022-09-06 20:26 UTC, Peter-Crawley requested changes

2022-09-06 20:26 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
clipboard.region.map

2022-09-06 20:26 UTC, Peter-Crawley commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
return if / else if / else ?:

2022-09-06 20:26 UTC, Peter-Crawley commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		CustomBlocks.MINERAL_URANIUM.block.blockData.material to 50.0,
the material of these will all be the same

2022-09-06 20:26 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		list.add("&7Cost&8: &6$${blueprintcost.roundToInt()}")
why not just .toInt()

2022-09-06 20:32 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
cant do return in there

2022-09-06 20:32 UTC, SciathGH commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
sure why not

2022-09-06 20:32 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		list.add("&7Cost&8: &6$${blueprintcost.roundToInt()}")
roundToInt is cleaner, but if u want sure

2022-09-06 20:34 UTC, trainb0y commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
return when :iq: /hj

2022-09-06 20:34 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
? you can map to an array of int and then use another function to add them all up

2022-09-06 20:34 UTC, SciathGH commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
not doing "else" it could cause anything not in there to be returned 0.1

2022-09-06 20:34 UTC, Peter-Crawley commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
cant use when there

2022-09-06 20:35 UTC, SciathGH commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		if(data.material.isGlass) return 0.1
i can do else if, so im going too

2022-09-06 20:36 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
That sounds like a waste of time, the way I originally have it works fine, and doesnt require any extra effort on anyones part

2022-09-06 20:37 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
cleaner

2022-09-06 20:41 UTC, SciathGH commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		for (vec in clipboard.region) {
Ok, how is it cleaner then 1 for loop?

2022-09-08 16:40 UTC, Peter-Crawley requested changes

2022-09-08 16:40 UTC, Peter-Crawley commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		when(data){
else when

2022-09-08 16:40 UTC, Peter-Crawley commented on src/main/kotlin/net/horizonsend/ion/core/ShipFactoryMaterialCosts.kt
> +		return blockprice[data.material] ?: 3.0
else if

2022-09-08 16:40 UTC, Peter-Crawley commented on src/main/kotlin/net/starlegacy/command/starship/BlueprintCommand.kt
> +		clipboard.region.map {it}.forEach {
i'll clean this up later

2022-09-11 17:42 UTC, Peter-Crawley commented
has this been tested?

2022-09-11 17:47 UTC, SciathGH commented
extensively
well that is before the clipboard.region.map{it}.foreach{} change but I dont see a reason why that would make a difference

2022-09-11 23:48 UTC, SciathGH commented
> has this been tested?

And also it wont break severely, since I last tested only the blueprint info could possibly break Which is both an easy fix, and not a detriment

2022-09-12 21:50 UTC, merged